feat(pre_commit) to run pa11y tests before running a commit

diff --git a/infra/dev/pre-commit b/infra/dev/pre-commit
--- a/infra/dev/pre-commit
+++ b/infra/dev/pre-commit
@@ -9,4 +9,10 @@ if [ $? -ne 0 ]; then
   exit 1;
 fi
 
+# ./infra/test/w3c.sh
+# if [ $? -ne 0 ]; then
+# 	echo "pa11y tests locally show errors. Please fix them before committing"
+#   exit 1;
+# fi
+
 exit 0
